# Generated by Django 5.1.3 on 2026-01-17 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='storage.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['name'],
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='MountedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mounted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounted_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Примонтированная папка',
                'verbose_name_plural': 'Примонтированные папки',
            },
        ),
        migrations.CreateModel(
            name='SharedFolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('email', 'По email'), ('link', 'По ссылке')], max_length=10)),
                ('share_token', models.CharField(blank=True, help_text='Токен для доступа по ссылке', max_length=64, null=True, unique=True)),
                ('max_users', models.IntegerField(default=0, help_text='Максимум пользователей (0 = неограничено)')),
                ('can_view', models.BooleanField(default=True, help_text='Может просматривать файлы')),
                ('can_download', models.BooleanField(default=True, help_text='Может скачивать файлы')),
                ('can_modify', models.BooleanField(default=False, help_text='Может изменять файлы')),
                ('can_delete', models.BooleanField(default=False, help_text='Может удалять файлы')),
                ('allow_unregistered_view', models.BooleanField(default=True, help_text='Незарегистрированные могут просматривать')),
                ('allow_unregistered_download', models.BooleanField(default=False, help_text='Незарегистрированные могут скачивать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_accesses', to='storage.folder')),
                ('granted_to_user', models.ForeignKey(blank=True, help_text='Пользователь, которому предоставлен доступ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_accesses', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к папке',
                'verbose_name_plural': 'Доступы к папкам',
                'unique_together': {('folder', 'granted_to_user'), ('folder', 'share_token')},
            },
        ),
        migrations.CreateModel(
            name='SharedFolderLinkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('share_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_users', to='storage.sharedfolderaccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_folder_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь с доступом по ссылке',
                'verbose_name_plural': 'Пользователи с доступом по ссылке',
                'unique_together': {('share_access', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название хранилища')),
                ('storage_type', models.CharField(choices=[('local', 'Локальное хранилище'), ('s3', 'S3 хранилище')], default='local', max_length=10, verbose_name='Тип хранилища')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('max_size', models.BigIntegerField(help_text='Максимальный размер хранилища в байтах', verbose_name='Максимальный размер (в байтах)')),
                ('priority', models.IntegerField(default=0, help_text='Чем выше число, тем выше приоритет при выборе хранилища', verbose_name='Приоритет')),
                ('local_path', models.CharField(blank=True, help_text='Абсолютный путь к директории хранилища', max_length=500, null=True, verbose_name='Локальный путь')),
                ('s3_access_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Access Key')),
                ('s3_secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Secret Key')),
                ('s3_bucket_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Bucket Name')),
                ('s3_endpoint_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='S3 Endpoint URL')),
                ('s3_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='S3 Region')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Хранилище',
                'verbose_name_plural': 'Хранилища',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
        migrations.AddField(
            model_name='userfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='storage.userfile'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('archive', 'Архив'), ('text', 'Текстовый файл'), ('document', 'Документ'), ('code', 'Код'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='userfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='storage.folder'),
        ),
        migrations.AddField(
            model_name='mountedfolder',
            name='shared_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounted_by', to='storage.sharedfolderaccess'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='storage.storage', verbose_name='Хранилище'),
        ),
        migrations.AlterUniqueTogether(
            name='mountedfolder',
            unique_together={('user', 'shared_access')},
        ),
    ]
