# Generated by Django 5.1.3 on 2024-11-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_downloadtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('other', 'Другое')], default='other', max_length=10),
        ),
    ]
