# Generated by Django 5.1.3 on 2026-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_folder_mountedfolder_sharedfolderaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='s3_access_key',
            field=models.CharField(blank=True, help_text='Access Key для S3-совместимого сервиса', max_length=255, null=True, verbose_name='Access Key ID'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='s3_bucket_name',
            field=models.CharField(blank=True, help_text='Имя bucket в S3-совместимом хранилище', max_length=255, null=True, verbose_name='Bucket Name'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='s3_endpoint_url',
            field=models.CharField(blank=True, help_text='URL эндпоинта (обязательно для не-Amazon сервисов: MinIO, DigitalOcean Spaces и т.д.)', max_length=500, null=True, verbose_name='Endpoint URL'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='s3_region',
            field=models.CharField(blank=True, help_text='Регион (опционально для некоторых сервисов)', max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='s3_secret_key',
            field=models.CharField(blank=True, help_text='Secret Key для S3-совместимого сервиса', max_length=255, null=True, verbose_name='Secret Access Key'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Локальное хранилище'), ('s3', 'S3-совместимое хранилище')], default='local', max_length=10, verbose_name='Тип хранилища'),
        ),
    ]
