# Generated by Django 5.1.3 on 2024-11-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_userfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfile',
            name='public_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
