<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_userfile_is_public_userfile_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='video_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='video_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfile',
            name='video_qualities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
=======
# Generated by Django 5.1.3 on 2024-11-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_userfile_is_public_userfile_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='video_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='video_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfile',
            name='video_qualities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
>>>>>>> a2370a2 (Initial commit)
