# Generated by Django 5.1.3 on 2024-11-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_userfile_video_duration_userfile_video_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='video_duration',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='video_processed',
        ),
        migrations.AlterField(
            model_name='userfile',
            name='video_qualities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
