<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_userfile_video_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='video_qualities',
        ),
    ]
=======
# Generated by Django 5.1.3 on 2024-11-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_userfile_video_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='video_qualities',
        ),
    ]
>>>>>>> a2370a2 (Initial commit)
