# Generated by Django 5.1.3 on 2024-11-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_userfile_video_duration_userfile_video_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='video_duration',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='video_processed',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='video_qualities',
        ),
    ]
