# Generated by Django 5.1.3 on 2024-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_folder_userfile_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='folder',
        ),
        migrations.AddField(
            model_name='userfile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
