# Generated by Django 5.1.3 on 2024-11-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_remove_userfile_folder_userfile_size_delete_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='size',
        ),
    ]
