# Generated by Django 5.1.3 on 2024-11-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_remove_userfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
