<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_alter_userfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('archive', 'Архив'), ('other', 'Другое')], default='other', max_length=10),
        ),
    ]
=======
# Generated by Django 5.1.3 on 2024-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_alter_userfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('archive', 'Архив'), ('other', 'Другое')], default='other', max_length=10),
        ),
    ]
>>>>>>> a2370a2 (Initial commit)
