<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_alter_userfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('file_path', models.FileField(upload_to='youtube_videos/')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
=======
# Generated by Django 5.1.3 on 2024-11-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_alter_userfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('file_path', models.FileField(upload_to='youtube_videos/')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
>>>>>>> a2370a2 (Initial commit)
