<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='developer_mode',
            field=models.BooleanField(default=False),
        ),
    ]
=======
# Generated by Django 5.1.3 on 2024-11-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='developer_mode',
            field=models.BooleanField(default=False),
        ),
    ]
>>>>>>> a2370a2 (Initial commit)
