# Generated by Django 5.1.3 on 2024-11-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site_name',
            field=models.CharField(default='eStorage', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site_name_color',
            field=models.CharField(default='#000000', help_text='HEX color code', max_length=7),
        ),
    ]
