<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0002_userprofile_developer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storage_quota',
            field=models.BigIntegerField(default=10737418240),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='storage_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
=======
# Generated by Django 5.1.3 on 2024-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0002_userprofile_developer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storage_quota',
            field=models.BigIntegerField(default=10737418240),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='storage_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
>>>>>>> a2370a2 (Initial commit)
