# Generated by Django 5.1.3 on 2024-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0002_userprofile_site_logo_userprofile_site_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_site_name', models.CharField(default='eStorage', max_length=100)),
                ('default_site_logo', models.ImageField(blank=True, null=True, upload_to='default_site_logo/')),
                ('default_site_name_color', models.CharField(default='#000000', max_length=7)),
                ('allow_registration', models.BooleanField(default=True)),
                ('default_storage_quota', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
