# Generated by Django 5.1.3 on 2024-11-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0003_systemsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='default_site_name',
            new_name='site_name',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='allow_registration',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='default_site_logo',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='default_site_name_color',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='default_storage_quota',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='site_logo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='site_name_color',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='system/logo/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_name_color',
            field=models.CharField(default='#ffffff', help_text='HEX color code', max_length=7),
        ),
    ]
