# Generated by Django 5.1.3 on 2024-11-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0003_userprofile_storage_quota_userprofile_storage_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='storage_used',
        ),
    ]
