<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0004_remove_userprofile_storage_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(default='#0d6efd', help_text='HEX color code', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
=======
# Generated by Django 5.1.3 on 2024-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0004_remove_userprofile_storage_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(default='#0d6efd', help_text='HEX color code', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
>>>>>>> a2370a2 (Initial commit)
