# Generated by Django 5.1.3 on 2024-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0004_rename_default_site_name_systemsettings_site_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_font',
            field=models.FileField(blank=True, help_text='Поддерживаемые форматы: TTF, OTF, WOFF, WOFF2', null=True, upload_to='fonts/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_family',
            field=models.CharField(blank=True, help_text='Название шрифта для CSS', max_length=100, null=True),
        ),
    ]
