<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0005_userprofile_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='content_opacity',
            field=models.FloatField(default=1.0, help_text='Прозрачность контентных блоков (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='navbar_opacity',
            field=models.FloatField(default=1.0, help_text='Прозрачность навигационной панели (0.0 - 1.0)'),
        ),
    ]
=======
# Generated by Django 5.1.3 on 2024-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0005_userprofile_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='content_opacity',
            field=models.FloatField(default=1.0, help_text='Прозрачность контентных блоков (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='navbar_opacity',
            field=models.FloatField(default=1.0, help_text='Прозрачность навигационной панели (0.0 - 1.0)'),
        ),
    ]
>>>>>>> a2370a2 (Initial commit)
