# Generated by Django 5.1.3 on 2024-11-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0005_userprofile_custom_font_userprofile_font_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='font_family',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='custom_font',
            field=models.FileField(blank=True, help_text='Поддерживаемые форматы: .ttf, .otf, .woff, .woff2', null=True, upload_to='fonts/'),
        ),
    ]
