# Generated by Django 5.1.3 on 2024-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0006_remove_userprofile_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_family_name',
            field=models.CharField(blank=True, help_text='Название шрифта для CSS', max_length=100, null=True),
        ),
    ]
