# Generated by Django 5.1.3 on 2024-11-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0006_userprofile_content_opacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='content_opacity',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='container_opacity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='navbar_opacity',
            field=models.FloatField(default=1.0),
        ),
    ]
