# Generated by Django 5.1.3 on 2024-11-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0007_remove_userprofile_content_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='container_color',
            field=models.CharField(default='#f8f9fa', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='navbar_color',
            field=models.CharField(default='#212529', max_length=7),
        ),
    ]
