# Generated by Django 5.1.3 on 2024-11-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0007_userprofile_font_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_format',
            field=models.CharField(blank=True, help_text='Формат шрифта для CSS (truetype, opentype, woff, woff2)', max_length=20, null=True),
        ),
    ]
