# Generated by Django 5.1.3 on 2024-12-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0008_userprofile_font_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='video_player',
            field=models.CharField(
                choices=[('plyr', 'Plyr'), ('native', 'HTML5 (Нативный)')],
                default='plyr',
                help_text='Выбор видео проигрывателя',
                max_length=20
            ),
        ),
    ]

