# Generated by Django 5.1.3 on 2024-11-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0008_userprofile_container_color_userprofile_navbar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_text_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='text_color',
            field=models.CharField(default='#000000', help_text='HEX color code', max_length=7),
        ),
    ]
