# Generated by Django 5.1.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0009_userprofile_video_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='proxy_url',
            field=models.CharField(blank=True, help_text='URL прокси-сервера для загрузки файлов (например: https://api.allorigins.win/raw?url= или https://corsproxy.io/?)', max_length=500, null=True),
        ),
    ]

