# Generated by Django 5.1.3 on 2024-11-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0010_adminrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminRole',
        ),
    ]
