# Generated by Django 5.1.3 on 2024-11-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventshock_auth', '0011_delete_adminrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ja', '日本語')], default='ru', max_length=2),
        ),
    ]
