from django.urls import path
from . import views
from .api import youtube

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('download/<str:token>/', views.download_file, name='download_file'),
    path('raw/<path:filename>/', views.raw_file, name='raw_file'),
    path('get-raw-link/<int:file_id>/', views.get_raw_link, name='get_raw_link'),
    path('delete/<int:file_id>/', views.delete_file, name='delete_file'),
    path('generate-link/<int:file_id>/', views.generate_download_link, name='generate_download_link'),
    path('save-text/<int:file_id>/', views.save_text_file, name='save_text_file'),
    path('archive-contents/<int:file_id>/', views.get_archive_contents, name='archive_contents'),
    path('extract-archive/<int:file_id>/', views.extract_archive, name='extract_archive'),
    path('toggle-publicity/<int:file_id>/', views.toggle_file_publicity, name='toggle_file_publicity'),
    path('public/metadata/<str:token>/', views.get_public_file_metadata, name='get_public_file_metadata'),
    path('public/<str:token>/', views.public_file, name='public_file'),
    path('bulk-delete/', views.bulk_delete, name='bulk_delete'),
    path('bulk-download/', views.bulk_download, name='bulk_download'),
    path('bulk-archive/', views.bulk_archive, name='bulk_archive'),
    path('stats/', views.storage_stats, name='storage_stats'),
    path('youtube/download/', views.download_youtube_video, name='youtube_download'),
    path('youtube/preview/', views.get_video_info, name='youtube_preview'),
    path('youtube/progress/', views.download_progress, name='youtube_progress'),
    path('youtube/videos/', views.video_list, name='video_list'),
    path('check-file/', views.check_file, name='check_file'),
    path('upload-chunk/<str:filename>/', views.upload_chunk, name='upload_chunk'),
    path('api/yt-download/', youtube.youtube_download, name='api_youtube_download'),
    path('api/yt-task/<int:task_id>/', youtube.task_status, name='api_task_status'),
    path('metadata/<int:file_id>/', views.get_file_metadata, name='get_file_metadata'),
    path('video-quality/<int:file_id>/<int:quality>/', views.get_video_quality, name='get_video_quality'),
    path('public/video-quality/<str:token>/<int:quality>/', views.get_public_video_quality, name='get_public_video_quality'),
    # Folder operations
    path('folder/create/', views.create_folder, name='create_folder'),
    path('folder/rename/<int:folder_id>/', views.rename_folder, name='rename_folder'),
    path('folder/delete/<int:folder_id>/', views.delete_folder, name='delete_folder'),
    path('folder/move-files/', views.move_files, name='move_files'),
    path('folder/tree/', views.get_folders_tree, name='get_folders_tree'),
    path('file/rename/<int:file_id>/', views.rename_file, name='rename_file'),
    # Share operations
    path('folder/share/<int:folder_id>/', views.share_folder_wizard, name='share_folder_wizard'),
    path('folder/share-email/<int:folder_id>/', views.share_folder_email, name='share_folder_email'),
    path('folder/share-link/<int:folder_id>/', views.share_folder_link, name='share_folder_link'),
    path('folder/revoke-access/<int:folder_id>/', views.revoke_folder_access, name='revoke_folder_access'),
    path('folder/update-permissions/<int:access_id>/', views.update_access_permissions, name='update_access_permissions'),
    path('shared-folders/', views.shared_folders_list, name='shared_folders_list'),
    path('folder/mount/<int:access_id>/', views.mount_folder, name='mount_folder'),
    path('folder/unmount/<int:mounted_id>/', views.unmount_folder, name='unmount_folder'),
    path('folder/link-users/<int:access_id>/', views.get_link_access_users, name='get_link_access_users'),
    path('shared/<str:token>/', views.shared_folder_view, name='shared_folder_view'),
    path('shared/<str:token>/download/<int:file_id>/', views.shared_file_download, name='shared_file_download'),
] 